import type { TranslationKey } from '../i18n/catalog';

export type UseRow = { file: string; key: TranslationKey };

export const R1_AUTH: UseRow[] = [
  { file: 'src/app/(auth)/login.tsx', key: 'login.invalidCredentials' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.signIn' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.email' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.password' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.signIn' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.createAccount' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.forgotPassword' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.forgotPassword' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.comingSoon' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.email' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.sendRecoveryLink' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.backToSignIn' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.emailAlreadyRegistered' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.createAccount' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.firstName' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.lastName' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.email' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.phone' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.password' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.confirmPassword' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.country' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.iAcceptTerms' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.createAccount' },
];

export const R2_TABS: UseRow[] = [
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.home' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.map' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.health' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.food' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.profile' },
];

export const R3_HOME: UseRow[] = [
  { file: 'src/app/(tabs)/home.tsx', key: 'home.noLocationDataYet' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.lastSeen' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.home' },
  { file: 'src/app/(tabs)/home.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/home.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/home.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/home.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/home.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.free' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.online' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.offline' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.noCollar' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.pairCollar' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.summaryTitle' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.activityNeedsCollar' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.couldNotLoadActivity' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.activity' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.sleep' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.distance' },
  { file: 'src/app/(tabs)/home.tsx', key: 'home.viewOnMap' },
];

export const R4_MAP: UseRow[] = [
  { file: 'src/app/(tabs)/map.tsx', key: 'map.justNow' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.agoMinutes' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.agoHours' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.noSignal' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.live' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.stale' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.trackingNeedsCollar' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.noLocationDataYet' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.speed' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.distance' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.updated' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.deactivateLostMode' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.activateLostMode' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.couldNotUpdateLostMode' },
];

export const R5_HEALTH: UseRow[] = [
  { file: 'src/app/(tabs)/health.tsx', key: 'health.health' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.vaccines' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.nextDue' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.noVaccinesYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.couldNotLoadVaccines' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.weight' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.noWeightEntriesYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.couldNotLoadWeight' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.weightLog' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.enterValidWeight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.errorForbidden' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.backToHealth' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weightLog' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weightKg' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.measuredAt' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.yyyyMmDd' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyCondition' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyConditionPlaceholder' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.logWeight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.noWeightEntriesYet' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyConditionValue' },
  { file: 'src/components/weight-chart.tsx', key: 'weightChart.notEnoughDataYet' },
];

export const R6_FOOD: UseRow[] = [
  { file: 'src/app/(tabs)/food.tsx', key: 'food.food' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyTarget' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyKcal' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyGrams' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealsToday' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.pending' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.served' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.aiRecommendation' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.noMealPlanYet' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.couldNotLoadPlan' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealSchedule' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealScheduleLinkSubtitle' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.errorForbidden' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.errorProfileRequired' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.registerWeightFirst' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.backToFood' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.mealSchedule' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.dailyTarget' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.dailyGrams' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.mealsPerDay' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.timesAndPortions' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.noMealPlanYet' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.generatePlan' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.nutritionProfile' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.noNutritionProfileYet' },
];

export const ALL_USES: UseRow[] = [
  ...R1_AUTH,
  ...R2_TABS,
  ...R3_HOME,
  ...R4_MAP,
  ...R5_HEALTH,
  ...R6_FOOD,
];

describe('#65: la tabla de uso de copy está disponible al runner', () => {
  it('expone al menos el primer lote normativo', () => {
    expect(ALL_USES.length).toBeGreaterThan(0);
  });
});
