import type { TranslationKey } from '../i18n/catalog';

export type UseRow = { file: string; key: TranslationKey };

export const R1_AUTH: UseRow[] = [
  { file: 'src/app/(auth)/login.tsx', key: 'login.invalidCredentials' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/login.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.signIn' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.email' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.password' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.signIn' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.createAccount' },
  { file: 'src/app/(auth)/login.tsx', key: 'login.forgotPassword' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.forgotPassword' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.comingSoon' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.email' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.sendRecoveryLink' },
  { file: 'src/app/(auth)/forgot.tsx', key: 'forgot.backToSignIn' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.emailAlreadyRegistered' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/register.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.createAccount' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.firstName' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.lastName' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.email' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.phone' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.password' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.confirmPassword' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.country' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.iAcceptTerms' },
  { file: 'src/app/(auth)/register.tsx', key: 'register.createAccount' },
];

export const R2_TABS: UseRow[] = [
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.home' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.map' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.health' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.food' },
  { file: 'src/components/floating-tab-bar.tsx', key: 'tabs.profile' },
];

export const R3_HOME: UseRow[] = [
  { file: 'src/screens/home/index.tsx', key: 'home.noLocationDataYet' },
  { file: 'src/screens/home/index.tsx', key: 'home.lastSeen' },
  { file: 'src/screens/home/index.tsx', key: 'home.home' },
  { file: 'src/screens/home/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/home/index.tsx', key: 'common.retry' },
  { file: 'src/screens/home/index.tsx', key: 'common.noPetsYet' },
  { file: 'src/screens/home/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/home/index.tsx', key: 'common.retry' },
  { file: 'src/screens/home/index.tsx', key: 'home.free' },
  { file: 'src/screens/home/index.tsx', key: 'home.online' },
  { file: 'src/screens/home/index.tsx', key: 'home.offline' },
  { file: 'src/screens/home/index.tsx', key: 'home.noCollar' },
  { file: 'src/screens/home/index.tsx', key: 'home.pairCollar' },
  { file: 'src/screens/home/index.tsx', key: 'home.summaryTitle' },
  { file: 'src/screens/home/index.tsx', key: 'home.activityNeedsCollar' },
  { file: 'src/screens/home/index.tsx', key: 'home.couldNotLoadActivity' },
  { file: 'src/screens/home/index.tsx', key: 'home.activity' },
  { file: 'src/screens/home/index.tsx', key: 'home.sleep' },
  { file: 'src/screens/home/index.tsx', key: 'home.distance' },
  { file: 'src/screens/home/index.tsx', key: 'home.weight' },
  { file: 'src/screens/home/index.tsx', key: 'home.viewOnMap' },
  { file: 'src/screens/home/index.tsx', key: 'home.walks' },
  { file: 'src/screens/home/index.tsx', key: 'home.quickActions' },
  { file: 'src/screens/home/index.tsx', key: 'home.quickActionWeight' },
  { file: 'src/screens/home/index.tsx', key: 'home.quickActionReminder' },
  { file: 'src/screens/home/index.tsx', key: 'home.quickActionDocuments' },
  { file: 'src/screens/home/index.tsx', key: 'home.reminders' },
  { file: 'src/screens/home/index.tsx', key: 'home.remindersSeeAll' },
  { file: 'src/screens/home/index.tsx', key: 'home.nextVaccineDays' },
  { file: 'src/screens/home/index.tsx', key: 'home.nextVaccineDaysLeft' },
  { file: 'src/screens/home/index.tsx', key: 'home.nextVaccineToday' },
  { file: 'src/screens/home/index.tsx', key: 'home.nextVaccineOverdue' },
  { file: 'src/screens/home/index.tsx', key: 'home.noUpcomingVaccine' },
  { file: 'src/screens/home/index.tsx', key: 'home.alertsBellUnread' },
  { file: 'src/screens/home/index.tsx', key: 'home.alertsBell' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.dayLabelMissing' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.dayLabelDistance' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.dayLabelWalks' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.dayLabelActiveMinutes' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.metricActiveMinutes' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.metricDistance' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.metricWalks' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.title' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.lastSevenDays' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.average' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.trend' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.chartSummary' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.noDataForDay' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'home.sleep' },
  { file: 'src/screens/home/weekly-activity-chart.tsx', key: 'weeklyActivity.noDataYet' },
];

export const R4_MAP: UseRow[] = [
  { file: 'src/app/(tabs)/map.tsx', key: 'map.justNow' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.agoMinutes' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.agoHours' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.noSignal' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.live' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.stale' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.trackingNeedsCollar' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/map.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.noLocationDataYet' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.speed' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.distance' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.updated' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.deactivateLostMode' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.activateLostMode' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.couldNotUpdateLostMode' },
  { file: 'src/app/(tabs)/map.tsx', key: 'map.gps' },
];

export const R5_HEALTH: UseRow[] = [
  { file: 'src/app/(tabs)/health.tsx', key: 'health.health' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.vaccines' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.nextDue' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.noVaccinesYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.couldNotLoadVaccines' },
  { file: 'src/app/(tabs)/health.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.weight' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.noWeightEntriesYet' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.couldNotLoadWeight' },
  { file: 'src/app/(tabs)/health.tsx', key: 'health.weightLog' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.enterValidWeight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.errorForbidden' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.backToHealth' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weightLog' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.weightKg' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.measuredAt' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.yyyyMmDd' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyCondition' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyConditionPlaceholder' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.logWeight' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.noWeightEntriesYet' },
  { file: 'src/app/(tabs)/weight-log.tsx', key: 'weightLog.bodyConditionValue' },
  { file: 'src/components/weight-chart.tsx', key: 'weightChart.notEnoughDataYet' },
];

export const R6_FOOD: UseRow[] = [
  { file: 'src/app/(tabs)/food.tsx', key: 'food.food' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.noPetsYet' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyTarget' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyKcal' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.dailyGrams' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealsToday' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.pending' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.served' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.aiRecommendation' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.noMealPlanYet' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.couldNotLoadPlan' },
  { file: 'src/app/(tabs)/food.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealSchedule' },
  { file: 'src/app/(tabs)/food.tsx', key: 'food.mealScheduleLinkSubtitle' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.errorForbidden' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.errorProfileRequired' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.registerWeightFirst' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.cannotReachServer' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.backToFood' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.mealSchedule' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'common.retry' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.dailyTarget' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.dailyGrams' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.mealsPerDay' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.timesAndPortions' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.noMealPlanYet' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.generatePlan' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.nutritionProfile' },
  { file: 'src/app/(tabs)/meal-schedule.tsx', key: 'mealSchedule.noNutritionProfileYet' },
];

export const R7_PROFILE: UseRow[] = [
  { file: 'src/screens/profile/index.tsx', key: 'profile.notRegistered' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.sterilized' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.notSterilized' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.ageMonths' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.errorPhotoFormat' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.couldNotUploadPhoto' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.couldNotUploadPhoto' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.couldNotUploadPhoto' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.profile' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.addPet' },
  { file: 'src/screens/profile/index.tsx', key: 'common.noPetsYet' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.couldNotLoadPets' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.couldNotLoadPet' },
  { file: 'src/screens/profile/index.tsx', key: 'common.retry' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.changePhoto' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.information' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.breed' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.microchip' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.gpsDevice' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.lastSignal' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.documents' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.gpsSettings' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.reminders' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.account' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.accountUnavailable' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.useDarkTheme' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.useLightTheme' },
  { file: 'src/screens/profile/index.tsx', key: 'profile.signOut' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.backToProfile' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.documentsOf' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.pet' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.noDocumentsYet' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.emptyBody' },
  { file: 'src/screens/docs/index.tsx', key: 'docs.couldNotLoadDocuments' },
  { file: 'src/screens/docs/index.tsx', key: 'common.retry' },
];

export const R8_REMINDERS: UseRow[] = [
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.errorForbidden' },
  { file: 'src/screens/reminders/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/reminders/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/reminders/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.reminders' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.new' },
  { file: 'src/screens/reminders/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/reminders/index.tsx', key: 'common.retry' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.noRemindersYet' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.active' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.thisWeek' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.inactive' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.upcoming' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.cancelled' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.sent' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.dueInDays' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.delete' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.deleteReminder' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.deleteSheetBody' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.delete' },
  { file: 'src/screens/reminders/index.tsx', key: 'reminders.cancel' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.vaccine' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.deworming' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.medication' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.appointment' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.weight' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.food' },
  { file: 'src/utils/reminder-meta.ts', key: 'reminderType.other' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.advanceSameDay' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.advance1Day' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.advance3Days' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.advance7Days' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.titleIsRequired' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.pickDate' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.dateMustBeFuture' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.errorForbidden' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.dateMustBeFuture' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.backToReminders' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.addReminder' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.type' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.title' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.reminderTitle' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.date' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.selectDate' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.time' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.alert' },
  { file: 'src/screens/add-reminder/index.tsx', key: 'addReminder.saveReminder' },
];

export const R9_ADD_PET: UseRow[] = [
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.errorPhotoFormat' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.nameIsRequired' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.chooseBirthDate' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.errorAgeRange' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.errorPhotoAfterCreate' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.checkPetDetails' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.youCannotCreatePet' },
  { file: 'src/screens/add-pet/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/add-pet/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/add-pet/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.backToProfile' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.addPet' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.pet' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.avatarPreview' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.choosePhoto' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.basicDetails' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.species' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.cat' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.dog' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.name' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.petName' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.breed' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.optional' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.sex' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.female' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.male' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.size' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.small' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.medium' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.large' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.medicalDetails' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.age' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.birthDate' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.approxMonths' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.selectBirthDate' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.months' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.sterilized' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.yes' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.optional' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.savePet' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.no' },
  { file: 'src/screens/add-pet/index.tsx', key: 'addPet.microchip' },
];

export const R10_PAIRING: UseRow[] = [
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorInvalidCode' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorAlreadyClaimed' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorPetHasDevice' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorNoSubscription' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorForbiddenClaim' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.errorForbiddenRelease' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.unpairAlertTitle' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.unpairAlertBody' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.cancel' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.unpair' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.back' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/pairing/index.tsx', key: 'common.retry' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.addPetFirst' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.trackerIsReady' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.readySubtitle' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.model' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.viewOnMap' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.done' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.pairCollar' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.freePlanPairPrompt' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.activationCode' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.printedOnCollarBox' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.pairCollar' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.gpsDevice' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.model' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.battery' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.connection' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.lastMessage' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.noMessagesYet' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.gpsTrackingActive' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.freePlanNoActivePlan' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.planStatusUnavailable' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.unpairCollar' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.esn' },
  { file: 'src/screens/pairing/index.tsx', key: 'pairing.esn' },
  { file: 'src/utils/device-connectivity.ts', key: 'deviceConnectivity.online' },
  { file: 'src/utils/device-connectivity.ts', key: 'deviceConnectivity.unknown' },
];

export const R11_RESET: UseRow[] = [
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.errorInvalidToken' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.errorExpiredToken' },
  { file: 'src/screens/reset-password/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/reset-password/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/reset-password/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.resetPassword' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.errorMissingToken' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.backToSignIn' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.resetPassword' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.passwordUpdated' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.backToSignIn' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.resetPassword' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.newPassword' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.confirmNewPassword' },
  { file: 'src/screens/reset-password/index.tsx', key: 'resetPassword.updatePassword' },
];

export const R12_ALERTS: UseRow[] = [
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.typeGeofenceExit' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.typeBatteryLow' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.typeUnknown' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.justNow' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.minutesAgo' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.hoursAgo' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.daysAgo' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.cannotReachServer' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.somethingWentWrong' },
  { file: 'src/screens/alerts/index.tsx', key: 'common.retry' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.empty' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.title' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.ack' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.statusAcked' },
  { file: 'src/screens/alerts/index.tsx', key: 'alerts.statusClosed' },
];

export const ALL_USES: UseRow[] = [
  ...R1_AUTH,
  ...R2_TABS,
  ...R3_HOME,
  ...R4_MAP,
  ...R5_HEALTH,
  ...R6_FOOD,
  ...R7_PROFILE,
  ...R8_REMINDERS,
  ...R9_ADD_PET,
  ...R10_PAIRING,
  ...R11_RESET,
  ...R12_ALERTS,
];

describe('#65: la tabla de uso de copy está disponible al runner', () => {
  it('expone al menos el primer lote normativo', () => {
    expect(ALL_USES.length).toBeGreaterThan(0);
  });

  // Enmienda (3): el candado es la consistencia interna, no una constante
  // escrita a mano — es la tercera vez que una cifra congelada envejece.
  it('cuadra ALL_USES con la suma de los doce bloques', () => {
    const blocks = [
      R1_AUTH, R2_TABS, R3_HOME, R4_MAP, R5_HEALTH, R6_FOOD,
      R7_PROFILE, R8_REMINDERS, R9_ADD_PET, R10_PAIRING, R11_RESET,
      R12_ALERTS,
    ];

    expect(ALL_USES).toHaveLength(
      blocks.reduce((total, block) => total + block.length, 0),
    );
  });
});
